name: BdsCore
file: Dockerfile
tag: bdsmaneger/core:dev
target: bdscore
buildx:
  enable: false
  platform: linux/amd64,linux/arm/v7,linux/arm64

# Docker Run envs
env:
  - name: DESCRIPTION
    value: Docker Test
  
  - name: WORLD_NAME
    value: Docker Run Test
  
  - name: GAMEMODE
    value: survival
  
  - name: DIFFICULTY
    value: normal
  
  - name: XBOX_ACCOUNT
    value: false
  
  - name: PLAYERS
    value: 5
  
  - name: BDS_VERSION
    value: latest

  - name: SERVER
    value: bedrock

# Docker Run Mount
mount: []

# Docker Run Ports
ports:
  - in: 19132
    out: 19132
    protocoll: udp
  - in: 1932
    out: 1932
    protocoll: tcp

# More options
options:
  build: []
  run:
    - "-v $(pwd)/Test:/root/bds_core"
  runArgv: []
