name: Publish dev npm package and Docker Image
on:
  push:
    branches:
      - main

env:
  DOCKER_ARCH: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Npm and Node Setup
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Edit Version
        uses: actions/github-script@v4
        id: set-result
        with:
          script: |
            const fs = require('fs');
            const Package_JSon = JSON.parse(fs.readFileSync(process.cwd()+'/package.json', 'utf8'));
            const run_ID = "${{ github.run_id }}";
            Package_JSon.version = `${run_ID.slice(0, 2)}.${run_ID.slice(3, 6)}.${run_ID.slice(7, 11)}`;
            fs.writeFileSync(process.cwd()+'/package.json', JSON.stringify(Package_Json, null, 2));
          result-encoding: string

      - name: Install Packages
        run: npm install

      - name: NPM Publish
        run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_ORG_TOKEN }}"

  docker_core:
    needs: [npm]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_ORG_USER }}
          password: ${{ secrets.DOCKER_ORG_PASS }}

      - name: checkout
        uses: actions/checkout@master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          target: bdscore
          tags: bdsmaneger/core:main
          platforms: ${{ env.DOCKER_ARCH }}

  docker_base:
    needs: [npm]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_ORG_USER }}
          password: ${{ secrets.DOCKER_ORG_PASS }}

      - name: checkout
        uses: actions/checkout@master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          target: bdsbase
          tags: |
            bdsmaneger/base:main
            bdsmaneger/node_image:main
          platforms: ${{ env.DOCKER_ARCH }}