  
name: Dev Publish
on: 
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/*/**'
      - 'package-lock.json'
      - '.devcontainer/**'
      - 'CHANGELOG.md'
jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      
      - name: Update Dependecies
        run: npm update

      - name: Install Depedencies
        run: npm install

      - name: Javascript Teste
        run: npm run test



  Npm-Publish:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master

      - name: Npm and Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org/

      - name: Edit Version
        run: |
          id_run1=$(echo ${{ github.run_id }} |cut -b 1-2)
          id_run2=$(echo ${{ github.run_id }} |cut -b 3-6)
          id_run3=$(echo ${{ github.run_id }} |cut -b 7-)
          old="$(cat package.json |grep "version"|head -1)"
          new_version="$id_run1.$id_run2.$id_run3"
          sed "s|$old|\"version\": \"$new_version\",|g" package.json > package2.json
          cat package2.json > package.json
          rm -rfv package2.json

      - name: Update Packages
        run: npm update

      - name: Install Packages
        run: npm install

      - name: Publish
        run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get Infos
        run: bash .github/workflows/get_version.sh

      - name: Tag
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Bds Maneger API v${{ env.bds_api_version }}
          tag_name: ${{ github.run_id }}
          prerelease: true
          body: |
            Install: npm install bds_maneger_api@dev
            Install: npm install bds_maneger_api@${{ env.bds_api_version }}
            Bds Maneger API publish Version (dev): ${{ env.bds_api_version }}
            Bds Maneger API depedencies: ${{ env.bds_api_depe }}