name: Publish
on:
  workflow_dispatch:
    inputs:  
      version:
        description: "Package version, dont includes 'v' or any other label"
        required: true
        type: "string"
      package_tag:
        description: "Package tag"
        required: true
        type: "string"
        default: "latest"
      publish_release:
        description: "Create tag on publish package"
        required: false
        default: true
        type: "boolean"

jobs:
  publish_package:
    runs-on: ubuntu-latest
    name: Publish Package (${{ matrix.npm_registry == 'NPM' && 'https://registry.npmjs.org/'|| 'https://npm.pkg.github.com/' }})
    strategy:
      matrix:
        npm_registry:
          - "Github"
          - "NPM"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "16.x"
          registry-url: ${{ matrix.npm_registry == 'NPM' && 'https://registry.npmjs.org/'|| 'https://npm.pkg.github.com/' }}

      - name: Update package.json
        shell: node {0}
        run: |
          const fs = require("fs");
          const path = require("path");
          const packagePath = path.join(process.cwd(), "package.json");
          const package = JSON.parse(fs.readFileSync(packagePath, "utf8"));
          package.version = "${{ github.event.inputs.version }}"
          fs.writeFileSync(packagePath, JSON.stringify(package, null, 2));

      - name: Install dependecies
        run: npm install

      - name: Build (typescript)
        run: npm run build

      - name: Publish
        run: npm publish --tag "${{ github.event.inputs.package_tag }}"
        env:
          NODE_AUTH_TOKEN: ${{ matrix.npm_registry == 'NPM' && secrets.NPM_ORG_TOKEN || secrets.GITHUB_TOKEN }}

  createRelease:
    if: ${{ github.event.inputs.publish_release }}
    name: Create release
    needs:
      - publish_package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "16.x"

      - name: Update package.json
        shell: node {0}
        run: |
          const fs = require("fs");
          const path = require("path");
          const packagePath = path.join(process.cwd(), "package.json");
          const package = JSON.parse(fs.readFileSync(packagePath, "utf8"));
          package.version = "${{ github.event.inputs.version }}"
          fs.writeFileSync(packagePath, JSON.stringify(package, null, 2));

      - name: Install dependencies
        run: npm install -no-save

      - name: Create Changelog
        run: |
          set -ex
          npm run release -- --version "${{ github.event.inputs.version }}"
          if git diff --name-only --exit-code; then
            echo "No changes to commit"
          else
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git config user.name "${{ github.actor }}"
            git add .
            git commit -m 'Release ${{ github.event.inputs.version }}'
            git push
          fi

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          draft: false