name: Publish Releases
on:
  release:
    types:
      - created

env:
  DOCKER_ARCH: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  npm:
    runs-on: ubuntu-latest
    if: ${{ github.actor }} == ${{ github.repository_owner }} && (contains('tag', ${{ github.ref }}) && contains('v', ${{ github.ref }}) || contains('V', ${{ github.ref }}))
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install Depedencies
        run: npm install --no-save

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_ORG_TOKEN }}'

      - name: Remove Dev Versions
        run: npm run remove_dev_versions
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_ORG_TOKEN }}'

  docker_core:
    needs: [npm]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout
        uses: actions/checkout@master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          target: bdscore
          tags: ghcr.io/the-bds-maneger/core:latest
          platforms: ${{ env.DOCKER_ARCH }}

  docker_base:
    needs: [npm]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_ORG_USER }}
          password: ${{ secrets.DOCKER_ORG_PASS }}

      - name: checkout
        uses: actions/checkout@master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          target: bdsbase
          tags: |
            ghcr.io/the-bds-maneger/base:latest
          platforms: ${{ env.DOCKER_ARCH }}
